# Generated by Django 3.2 on 2021-05-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('pay', models.IntegerField()),
                ('pub_date', models.DateTimeField()),
                ('body', models.TextField()),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
